language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: GLe7i9YfeQkqJyD1dxUWmTAKALOeD8F9sdzACaBohNRX5Hducr2LJplw3H24agYjj01smLOnQAXqUaMp3yZP/1EsNzVR+EyvaYUY4N08Ghz6hUN8NX0MD/eNxEhoeUt6jcyUcRYObxQlDTzVE+sYkzO/+gQ/+0LMDOnDQx191KA=
  - secure: j9RS7iEMk5cMwebqEvR2iBOTxY9uqYI7tz1/S0fYWRgnVzzSqhKjmcEK8/t6s7NFeKEDaJwl+yt9mhVYZD6Kiewh3SKyS7X2wuNGhKoXOZLZW9AU/+gUqiKHqDweTSxgN8GL14VhjaQXuF1b2n1/gdXbPjU18sHWE1JBN9UXH8o=
